### ISSUE TITLE
Tópico <2>

### ISSUE THREAD

**Issue by Paulo-del** [plinioleitao/bd-2022-1-bec#1]
Sobre as definições apresentadas:
**WIEDERHOLD**: Fala sobre o banco de dados ser algo que reúne dados que interagem entre si, ou seja, que todos influenciarão e serão influenciados por todos.

**CHU**: Fala sobre o banco de dados sem se distanciar da definição anterior apresentada.

**DATE**: Fala sobre o banco de dados apresentando nova definição quando introduz a qualidade _operacional_ aos dados que são armazenados no banco e a finalidade de uso por um sistema. Por operacional pode-se depreender a noção de manipulação, alteração, modificação dos mesmos dados se preciso for, propiciando o funcionamento de algo.

**SILBERCHATZ, KORTH, SUDARSHAN** - Trata o banco de dados também da perspectiva de uma coleção, mas mais para o armazenamento das coisas que permitirão ao empreendimento (negócio, empresa, companhia, ato realizado) se fazer conhecido.

**ENGLES** - Dá uma interpretação quase idêntica com a de Date: apesar de acrescentar a palavra "empresa" - restringindo a área de atuação dos "sistemas de aplicação" -, o sentido não muda, visto que na interpretação antecedente há restrição pelo particípio "determinada". Além disso, fala da qualidade operacional trazendo a ferramenta responsável por ela quando diz "sistema de aplicações".  

Um banco de dados é um espaço povoado de informações criado para uma determinada finalidade. Sendo um espaço, tem a possibilidade de comportar elementos. Sendo este espaço povoado, quer dizer que suas informações não cumprem meramente o papel de preencher, mas de crescer, produzir, criar laços entre si e até modificar este espaço, afinal é disso que se trata um povo. A finalidade de um banco de dados vai nortear como funcionará sua lógica estrutural, ou seja, o modo como se organizará de modo a atender a uma necessidade imposta na natureza dos dados que serão armazenados e relacionados, nas expectativas daquele que se interessou por adquirir um banco de dados para si, nas próprias condições da realidade do projeto a ser empreendido.

**_Usuário_**: aquele que se beneficiará do uso, neste caso, de uma ferramenta (software de gerenciamento de um banco de dados) conforme for conveniente às suas necessidades e propósitos. 

**_Acesso eficiente_**: Pressupondo uma devida organização das informações armazenadas no banco de dados, trata-se da facilidade, rapidez, precisão com que o usuário conseguirá chegar ao dado que lhe importa.

**Comment by plinioleitao** [comment]
COM APROVEITAMENTO.
