### ISSUE TITLE
Tópico 07

### ISSUE THREAD

**Issue by LucasSousaReis** [plinioleitao/bd-2022-1-bec#106]
(a) **Restrição de integridade de entidade**
(b) **Restrição de integridade referencial**
(c) **Esquema de banco de dados relacional**
(d) **Modelo Relacional**
(e) **Esquema de relação**
(f)  **Relação** 
(g) **Tupla**
(h) **Relação**
(i)  **Domínio de atributo**

**Comment by plinioleitao** [comment]
**Respostas:**

**(a)** Restrição de integridade de entidade
**(b)** Restrição de integridade referencial
**(c)** Esquema de banco de dados relacional
**(d)** Banco de dados vs. Instância de banco de dados
**(e)** Esquema de relação
**(f)** Relação
**(g)** Tupla ou n-tupla
**(h)** Relação
**(i)** Cardinalidade de domínio de atributo

COM APROVEITAMENTO.
