### ISSUE TITLE
Tópico 05

### ISSUE THREAD

**Issue by LucasSousaReis** [plinioleitao/bd-2022-1-bec#108]
O conceito de concurrency control se relaciona com as transações em um  sistema gerenciador de banco de dados (SGBD)  É um procedimento que em sistemas multiusuários nos auxilia no gerenciamento de dois processos simultâneos para execução sem conflitos entre si, utiliza técnicas de controle de concorrência para manter a consistência das transações.
Um exemplo: Caixas eletrônicos sem o uso de técnicas de concorrência podem apresentar inconsistência quando várias pessoas tentarem executar a mesma ação de saque em lugares diferentes
Por exemplo, se usarmos caixas eletrônicos e não usarmos concorrência, várias pessoas não poderão sacar dinheiro ao mesmo tempo em lugares diferentes. 
As vantagens do controle de concorrência são as seguintes: tempo de espera reduzido, menor tempo de resposta, melhor uso dos recursos,  melhoria no desempenho e eficiência.

Referências : https://www.tutorialspoint.com/what-is-concurrency-control-in-dbms

**Comment by plinioleitao** [comment]
Atividade postada fora do prazo.
Obs.: favor criar repositório, conforme Tópico 01.
