### ISSUE TITLE
Tópico 02

### ISSUE THREAD

**Issue by blkspiderick** [plinioleitao/bd-2022-1-bec#15]
**Questão 01**:

Banco de dados é uma coleção organizada de dados, que pode receber ações tais como: Inserção, Deleção, Modificação e Leitura. Essa coleção de dados poderá ser utilizada seja pelo usuário, para estabelecer relações de tabelas necessárias para o software que será criado ou já existente e também pelo sistema no qual aquele banco será direcionado, de forma a gravar, deletar, modificar ou apenas ler informações nas tabelas anteriormente mencionadas.

Portanto, o Banco de Dados mostra-se como uma Enciclopédia editável, que irá conter informações sobre ações realizadas no sistema e a arquitetura projetada para armazenar esses dados.

**Questão 02**:

Armazenamento de Grande Volume de Dados:

Esse termo, refere-se à capacidade que um banco de dados possui em relação ao armazenamento de informações. Isso se deve ás inúmeras tabelas e índices que podem ser relacionados e projetados para uma constante manutenção, fazendo com que o sistema possa acessar, modificar, inserir e deletar informações que não sejam relevantes ao utilizador naquele momento.

Acesso Eficiente:

Esse termo refere-se à maleabilidade de direcionamento de tabelas na relação entre sistema e banco de dados. Ao projetar uma nova função no sistema que necessite gravar ou alterar informações, são criadas novas tabelas específicas para aquela ação, da mesma forma que tabelas já existentes que possuem propósitos semelhantes também podem ser referenciadas. Dessa forma, ao gravar informações (Que serão utilizadas pelo sistema ou pelo usuário posteriormente) em tabelas específicas, o esforço de se localizar e alterar essas informações se torna mais preciso e prático.

**Comment by plinioleitao** [comment]
COM APROVEITAMENTO.
