### ISSUE TITLE
Topico 4

### ISSUE THREAD

**Issue by alvesrodrigo022** [plinioleitao/bd-2022-1-bec#69]
Markup languages - É uma linguagem de marcação que define um conjunto de regras nos quais direcionam as informações que podem serem incluídas na documentação relacionando com o conteúdo do facilitando o uso para o desenvolvedor. Temos ela de forma descritiva, definindo o procedimento ou apresentando algo. Relacionando a importância/semântica do conteúdo fornecendo instruções para que os programas processem os conteúdos do inicio ao fim seguindo o estipulado pela marcação. Exemplificam e rotulam os documentos diferenciando sua estrutura mostrando como deve ser tratado e interpretado. Exemplo ssão as tags de html, que definem a estrutura de texto, a importância e o que significa cada um quando requisitado pelos motores de busca dos navegadores.

**Comment by plinioleitao** [comment]
Referências ausentes.
SEM APROVEITAMENTO.
